
server:
  port: 8080
  shutdown: graceful

spring:
  application.name: simple-rate-retriever
  main.lazy-initialization: true
  metrics.prometheus.enabled: true
  web.resources.add-mappings: true
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:}
      roles: ADMIN
  boot.admin.client:
    enabled: false
    instance.metadata:
      user:
        name: ${spring.security.user.name}
        password: ${spring.security.user.password}

management:
  security.enabled: false
  endpoints:
    web.exposure.include: '*'
  distribution:
    percentiles-histogram:
      http.server.requests: true

simple-rate-retriever:
  fraction-digits: 4
  request-logging-filter.exclude:
    - '/actuator'
    - '/swagger-ui'
    - '/openapi.yml'
  providers:
    coin-market-cap:
      id: 'coinmarket'
      uri: 'https://pro-api.coinmarketcap.com/v1'
      api-key: ${CMC_API_KEY:}
    on-vista:
      id: 'stockexchange'
      uri: 'https://api.onvista.de/api/v1/instruments/query?limit=5&searchValue='

logging:
  level:
    com.github.spartusch: DEBUG
    de.codecentric: INFO
    org.springframework: INFO
