
server.port: 8080

spring:
  application.name: simple-rate-retriever
  metrics.prometheus.enabled: true

management:
  security.enabled: false
  endpoints:
    web.exposure.include: '*'
  distribution:
    percentiles-histogram:
      http.server.requests: true

simple-rate-retriever:
  fraction-digits: 4
  request-logging-filter.exclude: '/actuator'
  providers:
    coin-market-cap:
      id: 'coinmarket'
      uri: 'https://pro-api.coinmarketcap.com/v1'
      api-key: ${CMC_API_KEY:}
    on-vista:
      id: 'stockexchange'
      uri: 'https://www.onvista.de/api/header/search?q='

logging:
  level:
    com.github.spartusch: DEBUG
    de.codecentric: INFO
    org.springframework: INFO
