
server.port: 18091

spring:
  application.name: simple-rate-retriever
  metrics.prometheus.enabled: true

management:
  security.enabled: false
  endpoints:
    web.exposure.include: '*'
  distribution:
    percentiles-histogram:
      http.server.requests: true

simple-rate-retriever:
  request-logging-filter.exclude: '/actuator'
  provider:
    coin-market-cap.uri: 'https://api.coinmarketcap.com/v1/ticker/'
    on-vista.uri: 'https://www.onvista.de/api/header/search?q='

logging:
  level:
    org.springframework.web: INFO
