
server.port: 8090

provider:
  coinMarketCap.url: "https://api.coinmarketcap.com/v1/ticker/"
  onVista.url: "https://www.onvista.de/api/header/search?q="

logging.level.com.github.spartusch.rateretriever: INFO

spring:
    cache:
        cache-names: StockExchangeRateCache, CoinMarketRateCache
        caffeine:
            spec: expireAfterWrite=60s
