
server.port: 8090

spring:
  application.name: simple-rate-retriever
  metrics.prometheus.enabled: true
  cache:
    cache-names: StockExchangeRateCache, CoinMarketRateCache
    caffeine.spec: expireAfterWrite=60s

management:
  security.enabled: false
  endpoints:
    web.exposure.include: 'health, metrics, prometheus'
  distribution:
    percentiles-histogram:
      http.server.requests: true

provider:
  coinMarketCap.url: "https://api.coinmarketcap.com/v1/ticker/"
  onVista.url: "https://www.onvista.de/api/header/search?q="

requests.logging.suppressUserAgent: Prometheus
