
server.port: 18091

spring:
  application.name: simple-rate-retriever
  metrics.prometheus.enabled: true

management:
  security.enabled: false
  endpoints:
    web.exposure.include: '*'
  distribution:
    percentiles-histogram:
      http.server.requests: true

simple-rate-retriever:
  fraction-digits: 4
  request-logging-filter.exclude: '/actuator'
  providers:
    coin-market-cap:
      id: 'coinmarket'
      uri: 'https://api.coinmarketcap.com/v1/ticker/'
    on-vista:
      id: 'stockexchange'
      uri: 'https://www.onvista.de/api/header/search?q='

logging:
  level:
    org.springframework.web: INFO
