
server:
  port: 8080
  shutdown: graceful

spring:
  application.name: simple-rate-retriever
  main.lazy-initialization: true
  metrics.prometheus.enabled: true
  web.resources.add-mappings: true

management:
  security.enabled: false
  endpoints:
    web.exposure.include: health, info, loggers, prometheus, mappings
  distribution:
    percentiles-histogram:
      http.server.requests: true

simple-rate-retriever:
  fraction-digits: 4
  request-logging-filter.exclude:
    - '/actuator'
    - '/swagger-ui'
    - '/openapi.yml'
  providers:
    coin-market-cap:
      id: 'coinmarket'
      uri: 'https://pro-api.coinmarketcap.com/v1'
      api-key: ${CMC_API_KEY:}
    on-vista:
      id: 'stockexchange'
      uri: 'https://www.onvista.de/api/header/search?q='

logging:
  level:
    com.github.spartusch: DEBUG
    de.codecentric: INFO
    org.springframework: INFO
