
server.port: 18091

spring:
  application.name: simple-rate-retriever
  metrics.prometheus.enabled: true
  cache:
    cache-names: StockExchangeRateCache, CoinMarketRateCache
    caffeine.spec: expireAfterWrite=60s

management:
  security.enabled: false
  info.git.mode: full
  endpoints:
    web.exposure.include: '*'
  distribution:
    percentiles-histogram:
      http.server.requests: true

provider:
  coinMarketCap.url: 'https://api.coinmarketcap.com/v1/ticker/'
  onVista.url: 'https://www.onvista.de/api/header/search?q='

requestloggingfilter.exclude.path: '/actuator'
logging.file: simple-rate-retriever.log
