
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'simple-rate-retriever'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['localhost:18091']
      labels:
        application: simple-rate-retriever
